apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 577456190159.dkr.ecr.us-east-1.amazonaws.com/tomfem:1.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 255Mi
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

